### ISSUE TITLE
建议新增对goframe框架的内置支持

### ISSUE THREAD

**Issue by joyoes** [douyu/jupiter#10]
在“1.3.3 多服务端框架”建议增加对goframe框架的内置支持

**Comment by gorexlv** [comment]
很好的建议! 斗鱼内部也有定制的http框架以解决早期生态不健全的问题，随着生态的进步，我们更倾向于借助开源产品解决问题。goframe框架非常不错，谢谢你的建议。

期待您更多的宝贵意见。

**Comment by joyoes** [comment]
@gorexlv 计划在哪个版本开始支持内置gf框架啊？我好提前进入状态，写测试代码

**Comment by gorexlv** [comment]
@joyoes 目前我们内部还没这个计划。jupiter是从斗鱼内部框架孵化的，许多内部功能正等待整理和释放。所以排期上不太允许直接支持gf。

但是框架层面上，接入gf并不困难，如果您有意愿，时间也允许，很欢迎您来实现这个功能。深层次的治理规范和治理平台接入，如果有困难，我们很乐意协助您。

谢谢您的建议。
