### ISSUE TITLE
现在的文档是最新的吗？按照文档写demo调试不通

### ISSUE THREAD

**Issue by NacsonXXX** [douyu/jupiter#107]
clientCfg := clientEtcdv3.Config{
		Endpoints: []string{"127.0.0.1:2379"},
		ConnectTimeout:   time.Second * 3,
		Secure:    false,
	}
	etcCfg := etcdv3.Config{
		ReadTimeout: time.Second * 3,
		Prefix:  "jupiter",
		Config: &clientCfg,
	}
	resolver.Register(etcCfg.BuildResolver())
一直报错，卡在desugarLogger := logger.desugar.With(fields...)，原因是logger为nil;

	cron := config.Build()
	cron.AddFunc("*/1 * * * *", func() error {
		log.Println("hello")
		return nil
	})
	return app.Schedule(cron)
定时任务这么写，根本没有执行

**Comment by UnparalleledBeauty** [comment]
定时任务demo请参考

https://github.com/douyu/jupiter/tree/master/example/worker/cron

**Comment by zhangmingke** [comment]
> ```
> clientCfg := clientEtcdv3.Config{
> 	Endpoints: []string{"127.0.0.1:2379"},
> 	ConnectTimeout:   time.Second * 3,
> 	Secure:    false,
> }
> etcCfg := etcdv3.Config{
> 	ReadTimeout: time.Second * 3,
> 	Prefix:  "jupiter",
> 	Config: &clientCfg,
> }
> resolver.Register(etcCfg.BuildResolver())
> ```
> 
> 一直报错，卡在desugarLogger := logger.desugar.With(fields...)，原因是logger为nil;
> 
> ```
> cron := config.Build()
> cron.AddFunc("*/1 * * * *", func() error {
> 	log.Println("hello")
> 	return nil
> })
> return app.Schedule(cron)
> ```
> 
> 定时任务这么写，根本没有执行

目前您的这个问题解决了吗？

**Comment by zhangmingke** [comment]
> ```
> clientCfg := clientEtcdv3.Config{
> 	Endpoints: []string{"127.0.0.1:2379"},
> 	ConnectTimeout:   time.Second * 3,
> 	Secure:    false,
> }
> etcCfg := etcdv3.Config{
> 	ReadTimeout: time.Second * 3,
> 	Prefix:  "jupiter",
> 	Config: &clientCfg,
> }
> resolver.Register(etcCfg.BuildResolver())
> ```
> 
> 一直报错，卡在desugarLogger := logger.desugar.With(fields...)，原因是logger为nil;
> 
> ```
> cron := config.Build()
> cron.AddFunc("*/1 * * * *", func() error {
> 	log.Println("hello")
> 	return nil
> })
> return app.Schedule(cron)
> ```
> 
> 定时任务这么写，根本没有执行

目前您的这个问题解决了吗？

**Comment by kuange** [comment]
@NacsonXXX @zhangmingke

**Comment by kuange** [comment]
@NacsonXXX @zhangmingke 

定时任务配置需要开启 `withSeconds`

[jupiter.cron.default]
    withSeconds = true
    concurrentDelay= "5s"
    immediatelyRun = false


然后 添加的时候 第一个位置是秒，原因是 jupiter worker 源码没有给 config.parser 默认值，只有 `withSeconds` = true 的时候给了
```
cron.AddFunc("*/1 * * * * *", func() error {
	log.Println("hello")
	return nil
})
```

源码位置 https://github.com/douyu/jupiter/blob/6ccb1be0bc920a2118f4b0609758999aaf8764a4/pkg/worker/xcron/config.go#L90

**Comment by younglifestyle** [comment]
#180
