### ISSUE TITLE
jupiter user list

### ISSUE THREAD

**Issue by mlboy** [douyu/jupiter#109]
Welcome to use jupiter To know who is using it, pls append your org info as follow,
 
 * Organization：Douyu (Required)
 * Location: Wuhan, China（Required）
 * Contact:  [opensource@douyu.com](opensource@douyu.com) (Optional)
 * Purpose：used as our fundamental network transport lib (Required)
   Thanks again for your participation!
 
 欢迎使用jupiter，首先感谢你的使用，其次您可以参考下面的样例来提供您的信息以收集下使用场景：
 
 ```
 * 组织：斗鱼（Required）
 * 地点：中国武汉（Required）
 * 联系方式：opensource@douyu.com（Optional）
 * 场景：内部服务化改造（Required）
 ```
 
 再次感谢你的参与!!!

**Comment by zhangmingke** [comment]
组织: 斗鱼
地点：中国武汉
联系方式： 864325311@qq.com
场景：go语言应用rpc框架，go服务治理
