### ISSUE TITLE
建议增加权限管理casbin的示例或支持

### ISSUE THREAD

**Issue by joyoes** [douyu/jupiter#11]
建议增加权限管理casbin的示例或支持

**Comment by gorexlv** [comment]
架构目标上，jupiter更多的关注于微服务治理。权限管理相关的，我们认为在jupiter中直接支持不太好，未来可考虑通过其他方式比如独立的jupiter-contrib来做。

期待您更多的宝贵意见。

**Comment by askuy** [comment]
可以参考juno里面casbin用法。对菜单，接口，应用，环境的权限控制。
https://github.com/douyu/juno/blob/58cfc86ff05f46cb25adc867da5ce5de612a512f/internal/pkg/service/casbin/casbin.go
