### ISSUE TITLE
Go install toolkit ERROR? How to fix it?

### ISSUE THREAD

**Issue by RegiaYoung** [douyu/jupiter#1108]
$ go install github.com/douyu/jupiter/cmd/jupiter@latest
go: downloading github.com/douyu/jupiter v0.11.15
go: github.com/douyu/jupiter/cmd/jupiter@latest: zip: not a valid zip file

go version 1.18.10, something wrong with that

**Comment by sb981335043** [comment]
And one more quesion，can jupiter uses for GPU tasks, limiting the number of GPUs used by the user
