### ISSUE TITLE
support custom etcd log

### ISSUE THREAD

**Issue by askuy** [douyu/jupiter#112]
## Issue Description
user cannot set custom etcd log
![image](https://user-images.githubusercontent.com/14119383/87750809-0e783b00-c82f-11ea-8c80-fe07b3fc061f.png)
we need to expose the etcd log configuration 
support debug etcd client info like this

![image](https://user-images.githubusercontent.com/14119383/87750977-821a4800-c82f-11ea-8733-f02e2151d9f9.png)

Type: *feature request*

**Comment by 741369** [comment]
I will fix this issue later

**Comment by askuy** [comment]
> I will fix this issue later

welcome

**Comment by mlboy** [comment]
> I will fix this issue later

how is it going ?
