### ISSUE TITLE
微信群，好像过期了，是否可以更新？

### ISSUE THREAD

**Issue by Alvazz** [douyu/jupiter#113]
如题！

正在研究Go的相关微服务框架，想加入社群，了解更多。

希望能及时更新微信二维码，谢谢！

**Comment by zhangmingke** [comment]
> 如题！
> 
> 正在研究Go的相关微服务框架，想加入社群，了解更多。
> 
> 希望能及时更新微信二维码，谢谢！

好的

**Comment by zhangmingke** [comment]
> > 如题！
> > 正在研究Go的相关微服务框架，想加入社群，了解更多。
> > 希望能及时更新微信二维码，谢谢！
> 
> 好的

已经更新了

**Comment by yuanxuzhang** [comment]
网站微信扫码群过期了，如何加群？
