### ISSUE TITLE
[BUG] tools jupiter package 

### ISSUE THREAD

**Issue by ccb1900** [douyu/jupiter#119]
## Issue Description

Type: *bug report*

### Describe what happened
```
go: github.com/douyu/jupiter/tools/jupiter upgrade => v0.0.0-20200720175957-6ccb1be0bc92
go: finding module for package github.com/urfave/cli
go: finding module for package github.com/gobuffalo/packr/v2
go: finding module for package github.com/douyu/jupiter/pkg/util/xcolor
go: finding module for package github.com/gobuffalo/packr/v2/file/resolver
go: finding module for package github.com/emicklei/proto
go: finding module for package github.com/douyu/jupiter/pkg/util/xregexp
go: found github.com/urfave/cli in github.com/urfave/cli v1.22.4
go: found github.com/douyu/jupiter/pkg/util/xcolor in github.com/douyu/jupiter v0.1.0
go: found github.com/gobuffalo/packr/v2 in github.com/gobuffalo/packr/v2 v2.8.0
go: found github.com/emicklei/proto in github.com/emicklei/proto v1.9.0
go: github.com/sirupsen/logrus upgrade => v1.6.0
go: downloading github.com/russross/blackfriday/v2 v2.0.0
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: golang.org/x/sys upgrade => v0.0.0-20200720211630-cb9d2d5c5666
go: golang.org/x/crypto upgrade => v0.0.0-20200709230013-948cd5f35899
go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
go: github.com/karrick/godirwalk upgrade => v1.15.6
go get: upgrading github.com/russross/blackfriday/v2@v2.0.1: missing github.com/russross/blackfriday/go.mod and .../v2/go.mod at revision v2.0.0
```

### How to reproduce it (as minimally and precisely as possible)

just run 
```
go get -u github.com/douyu/jupiter/tools/jupiter
```

#### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 darwin/amd64
</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ccb/Library/Caches/go-build"
GOENV="/Users/ccb/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ccb/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kv/nz0sggtx5qn8st6p7fz0fhpm0000gn/T/go-build699359256=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### Anything else we need to know?

goproxy 开始没有加direct，
```
go get github.com/douyu/jupiter/tools/jupiter: module github.com/douyu/jupiter/tools/jupiter: reading https://mirrors.aliyun.com/goproxy/github.com/douyu/jupiter/tools/jupiter/@v/list: 404 Not Found
```

加了direct之后就是开头的样子。

**Comment by mlboy** [comment]
我并没有复现到，我用的是goproxy.cn镜像，你可以切换到 goproxy.cn镜像试试
```
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct

go get -u github.com/douyu/jupiter/tools/jupiter
```

```
go: downloading github.com/douyu/jupiter v0.1.0
go: downloading github.com/douyu/jupiter/tools/jupiter v0.0.0-20200720175957-6ccb1be0bc92
go: github.com/douyu/jupiter/tools/jupiter upgrade => v0.0.0-20200720175957-6ccb1be0bc92
go: finding module for package github.com/urfave/cli
go: finding module for package github.com/gobuffalo/packr/v2
go: finding module for package github.com/douyu/jupiter/pkg/util/xcolor
go: finding module for package github.com/emicklei/proto
go: finding module for package github.com/douyu/jupiter/pkg/util/xregexp
go: finding module for package github.com/gobuffalo/packr/v2/file/resolver
go: found github.com/urfave/cli in github.com/urfave/cli v1.22.4
go: found github.com/douyu/jupiter/pkg/util/xcolor in github.com/douyu/jupiter v0.1.0
go: found github.com/gobuffalo/packr/v2 in github.com/gobuffalo/packr/v2 v2.8.0
go: found github.com/emicklei/proto in github.com/emicklei/proto v1.9.0
go: github.com/karrick/godirwalk upgrade => v1.15.6
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: golang.org/x/sys upgrade => v0.0.0-20200720211630-cb9d2d5c5666
go: golang.org/x/crypto upgrade => v0.0.0-20200709230013-948cd5f35899
go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
go: github.com/sirupsen/logrus upgrade => v1.6.0
go: downloading golang.org/x/crypto v0.0.0-20200709230013-948cd5f35899
go: downloading golang.org/x/sys v0.0.0-20200720211630-cb9d2d5c5666
```

**Comment by ccb1900** [comment]
> 我并没有复现到，我用的是goproxy.cn镜像，你可以切换到 goproxy.cn镜像试试
> 
> ```
> go env -w GO111MODULE=on
> go env -w GOPROXY=https://goproxy.cn,direct
> 
> go get -u github.com/douyu/jupiter/tools/jupiter
> ```
> 
> ```
> go: downloading github.com/douyu/jupiter v0.1.0
> go: downloading github.com/douyu/jupiter/tools/jupiter v0.0.0-20200720175957-6ccb1be0bc92
> go: github.com/douyu/jupiter/tools/jupiter upgrade => v0.0.0-20200720175957-6ccb1be0bc92
> go: finding module for package github.com/urfave/cli
> go: finding module for package github.com/gobuffalo/packr/v2
> go: finding module for package github.com/douyu/jupiter/pkg/util/xcolor
> go: finding module for package github.com/emicklei/proto
> go: finding module for package github.com/douyu/jupiter/pkg/util/xregexp
> go: finding module for package github.com/gobuffalo/packr/v2/file/resolver
> go: found github.com/urfave/cli in github.com/urfave/cli v1.22.4
> go: found github.com/douyu/jupiter/pkg/util/xcolor in github.com/douyu/jupiter v0.1.0
> go: found github.com/gobuffalo/packr/v2 in github.com/gobuffalo/packr/v2 v2.8.0
> go: found github.com/emicklei/proto in github.com/emicklei/proto v1.9.0
> go: github.com/karrick/godirwalk upgrade => v1.15.6
> go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
> go: golang.org/x/sys upgrade => v0.0.0-20200720211630-cb9d2d5c5666
> go: golang.org/x/crypto upgrade => v0.0.0-20200709230013-948cd5f35899
> go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
> go: github.com/sirupsen/logrus upgrade => v1.6.0
> go: downloading golang.org/x/crypto v0.0.0-20200709230013-948cd5f35899
> go: downloading golang.org/x/sys v0.0.0-20200720211630-cb9d2d5c5666
> ```

换了 goproxy.cn 好了 ，谢谢

**Comment by askuy** [comment]
https://github.com/zouyx/agollo/issues/84#issuecomment-562425987

这是阿里云代理问题，请使用https://gproxy.cn

**Comment by ccb1900** [comment]
> [zouyx/agollo#84 (comment)](https://github.com/zouyx/agollo/issues/84#issuecomment-562425987)
> 
> 这是阿里云代理问题，请使用https://gproxy.cn

我记得文档写的是阿里云的代理，可以修改一下。
