### ISSUE TITLE
建议增加swagger示例或自动生成文档功能

### ISSUE THREAD

**Issue by forging2012** [douyu/jupiter#12]
建议增加swagger示例或自动生成文档功能

**Comment by 741369** [comment]
@gorexlv 这个swagger文档我可以帮忙加提PR吗？

**Comment by gorexlv** [comment]
> @gorexlv 这个swagger文档我可以帮忙加提PR吗？

@741369 可以的。非常欢迎

**Comment by forging2012** [comment]
可以参考faygo框架，通过struct注解，自动生成swagger文档，挺方便的。
https://github.com/henrylee2cn/faygo
https://github.com/henrylee2cn/faygo/blob/ed19f780b274c9867d924689344653b7717a10aa/apiware/paramapi.go

**Comment by 741369** [comment]
> 可以参考faygo框架，通过struct注解，自动生成swagger文档，挺方便的。
> https://github.com/henrylee2cn/faygo
> https://github.com/henrylee2cn/faygo/blob/ed19f780b274c9867d924689344653b7717a10aa/apiware/paramapi.go

兄弟，斗鱼这个开源是微服务管理工具，并没有提供很多外网API接口，只有一些example里面有一些简单的接口，通过swagger给谁生成文档呢？ @forging2012

**Comment by askuy** [comment]
> > 可以参考faygo框架，通过struct注解，自动生成swagger文档，挺方便的。
> > https://github.com/henrylee2cn/faygo
> > https://github.com/henrylee2cn/faygo/blob/ed19f780b274c9867d924689344653b7717a10aa/apiware/paramapi.go
> 
> 兄弟，斗鱼这个开源是微服务管理工具，并没有提供很多外网API接口，只有一些example里面有一些简单的接口，通过swagger给谁生成文档呢？ @forging2012

@741369 jupiter里面有http接口，可以搞个swagger。后面我们的juno系统的api文档，就可以用swagger生成。http://jupiter.douyu.com/juno/12.1apiauth.html#_12-1-1-%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA-api-token

**Comment by Mrliu8023** [comment]
`swagger`+`yapi`也很不错。

**Comment by liyue201** [comment]
@741369  我已经加了gin的swagger例子，echo的看看，差不多的吧
