### ISSUE TITLE
建议loadConfig函数改成可配置的

### ISSUE THREAD

**Issue by liyue201** [douyu/jupiter#126]
loadConfig函数支持http和文件作为配置源，建议改成可以自定义的函数加载任意配置源

https://github.com/douyu/jupiter/blob/97443349cf2dc7a5d8b4df08c1c4af552aa5198a/jupiter.go#L367

**Comment by mlboy** [comment]
能描述一下使用场景吗？
现在好多配置都依赖于现有配置格式，若提供自定义加载方法，恐怕兼容配置是个问题。

**Comment by liyue201** [comment]
> 能描述一下使用场景吗？
> 现在好多配置都依赖于现有配置格式，若提供自定义加载方法，恐怕兼容配置是个问题。
> 
> 最多只能暴露datasource provider
> 
> 或者通过类似指定协议的方式 scheme://xxxx
> 
> 控制scheme 去选择是 http/file/etcd
> 
> http://xxxx.com/config
> 
> file://xxx/xxx?relative=1
> 
> etcd://xxx/xxx/key

假设使用scheme，如何用户想使用这个函数中没有实现的scheme 怎么办，只能fork项目改框架代码。 而且etcd的配置中可能还有密码之类的敏感数据，放在启动参数中不合适

**Comment by liyue201** [comment]
找到了一个思路

这个pr修改
https://github.com/douyu/jupiter/pull/128#issue-458260284

**Comment by liyue201** [comment]
已提交到分支 feat/optimize
