### ISSUE TITLE
[BUG]文档疑问

### ISSUE THREAD

**Issue by 0102redirects** [douyu/jupiter#127]
希望可以完善下文档。
1.治理路由404：
http://jupiter.douyu.com/jupiter/5.1governintro.html

2.建议完善http api权限校验文档，目前的文档看完还是不知如何使用。

谢谢

**Comment by mlboy** [comment]
1, 文档本身可以查看， 只是在跳转github上有些问题，如“在github.com上编辑此页” 按钮链接中缺少github新版发master/tree 之类的路径，如急需可自行参考补充。
