### ISSUE TITLE
Redirect grpc log to outside

### ISSUE THREAD

**Issue by liyue201** [douyu/jupiter#140]
## Issue Description

Type: *feature request*

### Describe what feature you want

The package `google.golang.org/grpc/grpclog` defines the interface loggerv2 and function [SetLoggerV2](https://github.com/grpc/grpc-go/blob/8bec2f5d898fdbcbc4dbfc486df8a7d4a7219a39/grpclog/loggerv2.go#L69) to customize log output.  We can implement a logger struct to redirect grpc log to outside.

**Comment by askuy** [comment]
good idea, do you want to support this?

**Comment by liyue201** [comment]
grpclog 这个包是全局的， 找不到合适的地方去调这个函数SetLoggerV2，有什么建议吗

**Comment by askuy** [comment]
> grpclog 这个包是全局的， 找不到合适的地方去调这个函数SetLoggerV2，有什么建议吗

可以先把debug模式，grpc的调试日志进行输出
```
v1 := log.New(os.Stdout, "", log.Ldate|log.Ltime|log.Lmicroseconds).Writer()
v2 := grpclog.NewLoggerV2(v1, v1, v1)
grpclog.SetLoggerV2(v2)
```
非debug模式的grpc，我们之前拦截器里记录的grpc日志，基本可以满足需求了。

不过可以多看下grpc log记录的地方，看有没有一些日志很重要，需要放到线上日志里。
