### ISSUE TITLE
Development Manual

### ISSUE THREAD

**Issue by mlboy** [douyu/jupiter#145]
##  How to be a contributor

Contributions are always welcomed!

Contributions are not limited to code. We welcome any kind of contribution, such as:
 
 * Typo fix or code reformat
 * Document refinement
 * Answer the questions
 * Write blog posts about jupiter.
 * Test case supplement.
 * Fix bugs. 
 * Improve existing features, or develop new features.
 * Participate in new feature discussions and code review

More: https://github.com/douyu/jupiter/blob/master/CONTRIBUTING.md

Read this note, your will get a quick merge. 

## Coding Recommend:

For keep consistent code style, We expect only the following packages:

Unit Test:

- assist package:   github.com/stretchr/testify/assert
- mock package:   github.com/golang/mock/gomock 

Format:
- go fmt -d -s .

##  Build Something Awesome Together 

[![Stargazers over time](https://starchart.cc/douyu/jupiter.svg)](https://starchart.cc/douyu/jupiter)

**Comment by isfk** [comment]
3.0 完美继承了 2.0 Tab 标签页  滑动切换 需要用很大力的缺点...
为啥不能很轻盈的滑动呢
