### ISSUE TITLE
yaml拼写错误？

### ISSUE THREAD

**Issue by JasonWung** [douyu/jupiter#15]
是不是拼错了？
![image](https://user-images.githubusercontent.com/7370731/83473011-2e3fe380-a4bb-11ea-92cb-1d206be4090f.png)

**Comment by daydaygo** [comment]
文档是否可以用 gitbook/docify 等工具, 可以直接 github 提 pr, 修改类似的拼写错误

**Comment by xuchaojie** [comment]
> 页面左下角有 `在 github 上编辑此页`, 类似拼写错误可以直接提 pr

尝试了下，直接`404`了

**Comment by askuy** [comment]
已修复
