### ISSUE TITLE
[BUG] 当主机有多个网卡时，governor服务 panic

### ISSUE THREAD

**Issue by liyue201** [douyu/jupiter#159]
F:\code\go\jupiter\example\http\register>go run main.go --config=config.toml

 ```
panic:
    msg: governor start error
    loc: F:/code/go/jupiter/pkg/server/governor/server.go:23
    error: listen tcp4 169.254.98.129:19090: bind: The requested address is not valid in its context.
1597118095      PANIC   governor start error                    {"error": "listen tcp4 169.254.98.129:19090: bind: The requested address is
not valid in its context."}
github.com/douyu/jupiter/pkg/xlog.(*Logger).Panic
        F:/code/go/jupiter/pkg/xlog/log.go:325
github.com/douyu/jupiter/pkg/xlog.Panic
        F:/code/go/jupiter/pkg/xlog/api.go:65
github.com/douyu/jupiter/pkg/server/governor.newServer
        F:/code/go/jupiter/pkg/server/governor/server.go:23
github.com/douyu/jupiter/pkg/server/governor.(*Config).Build
        F:/code/go/jupiter/pkg/server/governor/config.go:67
github.com/douyu/jupiter.(*Application).initGovernor
        F:/code/go/jupiter/jupiter.go:349
github.com/douyu/jupiter/pkg/util/xgo.try
        F:/code/go/jupiter/pkg/util/xgo/init.go:47
github.com/douyu/jupiter/pkg/util/xgo.SerialUntilError.func1
        F:/code/go/jupiter/pkg/util/xgo/serial.go:36
github.com/douyu/jupiter.(*Application).startup.func1
        F:/code/go/jupiter/jupiter.go:145
sync.(*Once).doSlow
        D:/Go/src/sync/once.go:66
sync.(*Once).Do
        D:/Go/src/sync/once.go:57
github.com/douyu/jupiter.(*Application).startup
        F:/code/go/jupiter/jupiter.go:135
github.com/douyu/jupiter.(*Application).Startup
        F:/code/go/jupiter/jupiter.go:153
main.NewEngine
        F:/code/go/jupiter/example/http/register/main.go:44

```

**Comment by liyue201** [comment]
比如windows上安装虚拟机后，获取到的ip有可能是虚拟机的网卡ip

**Comment by mlboy** [comment]
虚拟网卡信息能贴下吗？

**Comment by liyue201** [comment]
> 虚拟网卡信息能贴下吗？

 ```
F:\code\go\jupiter-fat\example>ipconfig

Windows IP 配置


以太网适配器 本地连接 3:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 Npcap Loopback Adapter:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::393f:6864:5652:b0b4%25
   自动配置 IPv4 地址  . . . . . . . : 169.254.176.180
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 本地连接:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::2965:67b1:faf6:405f%11
   IPv4 地址 . . . . . . . . . . . . : 10.1.2.24
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 10.1.2.1

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::884a:c942:8c69:63b2%20
   IPv4 地址 . . . . . . . . . . . . : 192.168.74.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VirtualBox Host-Only Network:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::2145:749d:2a91:b77b%23
   自动配置 IPv4 地址  . . . . . . . : 169.254.183.123
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 VirtualBox Host-Only Network #2:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::29a2:a274:edf7:cd8c%24
   IPv4 地址 . . . . . . . . . . . . : 192.168.99.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

 ```

**Comment by younglifestyle** [comment]
我这里好像没有复现，当然我这里只有Vmware虚拟网卡，但我查看代码发现，当检测到网卡超过1的时候，它应该是自动绑定的localhost，我看你给出的网卡数有很多，但panic打印却是绑定的169.254.98.129:19090，有点疑惑。
func DefaultConfig() *Config {
	ips := xnet.GetIPs()
	if len(ips) == 0 {
		xlog.JupiterLogger.Error("govern get local ip error")
	}
	var host string
	if len(ips) == 1 {
		host = ips[0]
	} else {
		host = "localhost"
	}
}

**Comment by liyue201** [comment]
> 我这里好像没有复现，当然我这里只有Vmware虚拟网卡，但我查看代码发现，当检测到网卡超过1的时候，它应该是自动绑定的localhost，我看你给出的网卡数有很多，但panic打印却是绑定的169.254.98.129:19090，有点疑惑。
> func DefaultConfig() *Config {
> ips := xnet.GetIPs()
> if len(ips) == 0 {
> xlog.JupiterLogger.Error("govern get local ip error")
> }
> var host string
> if len(ips) == 1 {
> host = ips[0]
> } else {
> host = "localhost"
> }
> }

你的代码不是最新的master

**Comment by younglifestyle** [comment]
> > 我这里好像没有复现，当然我这里只有Vmware虚拟网卡，但我查看代码发现，当检测到网卡超过1的时候，它应该是自动绑定的localhost，我看你给出的网卡数有很多，但panic打印却是绑定的169.254.98.129:19090，有点疑惑。
> > func DefaultConfig() *Config {
> > ips := xnet.GetIPs()
> > if len(ips) == 0 {
> > xlog.JupiterLogger.Error("govern get local ip error")
> > }
> > var host string
> > if len(ips) == 1 {
> > host = ips[0]
> > } else {
> > host = "localhost"
> > }
> > }
> 
> 你的代码不是最新的master

是的，按照最新的代码，则会有这个问题

**Comment by younglifestyle** [comment]
conn, err := net.Dial("udp", "8.8.8.8:80")
	if err != nil {
		panic(err)
	}
	defer conn.Close()
	localAddr := conn.LocalAddr().(*net.UDPAddr)

使用上述代码可以拿到当前机器，连接网络的IP，不会造成拿错地址的情况，在有虚拟网卡的测试环境下测试。

**Comment by liyue201** [comment]
> ```
> conn, err := net.Dial("udp", "8.8.8.8:80")
> if err != nil {
> 	panic(err)
> }
> defer conn.Close()
> localAddr := conn.LocalAddr().(*net.UDPAddr)
> ```
> 
> 使用上述代码可以拿到当前机器，连接网络的IP，不会造成拿错地址的情况，在有虚拟网卡的测试环境下测试。

8.8.8.8是公网地址，在不连外网情况下，不行吧。 很多公司的服务器都是不给连外网的。

**Comment by liyue201** [comment]
多网卡的时候，可以通过配置CIDR获取本地ip，CIDR代表网卡所在的区域网。 这个在容器中也能使用，一般部署k8s的时候，都会有CIDR。

```go
// GetLocalIPInSubnet gets local ip in cidr
// cidr is a string of the format 192.168.1.0/24
func GetLocalIPInSubnet(cidr string) (string, error) {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return "", err
	}
	strnet := strings.Split(cidr, "/")
	if len(strnet) != 2 {
		return "", errors.New("cidr format error")
	}
	netseg := strnet[0]
	ones, _ := strconv.Atoi(strnet[1])

	mask := net.CIDRMask(ones, 32)
	for _, address := range addrs {
		if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			if ipnet.IP.To4() != nil && ipnet.IP.Mask(mask).String() == netseg {
				return ipnet.IP.String(), nil
			}
		}
	}
	return "", errors.New("unable to determine local ip")
}
```

**Comment by younglifestyle** [comment]
> > ```
> > conn, err := net.Dial("udp", "8.8.8.8:80")
> > if err != nil {
> > 	panic(err)
> > }
> > defer conn.Close()
> > localAddr := conn.LocalAddr().(*net.UDPAddr)
> > ```
> > 
> > 
> > 使用上述代码可以拿到当前机器，连接网络的IP，不会造成拿错地址的情况，在有虚拟网卡的测试环境下测试。
> 
> 8.8.8.8是公网地址，在不连外网情况下，不行吧。 很多公司的服务器都是不给连外网的。

因为用的UDP，所以不会真去连接到外网的，即使连接不到外网也可以的。

**Comment by liyue201** [comment]
> > > ```
> > > conn, err := net.Dial("udp", "8.8.8.8:80")
> > > if err != nil {
> > > 	panic(err)
> > > }
> > > defer conn.Close()
> > > localAddr := conn.LocalAddr().(*net.UDPAddr)
> > > ```
> > > 
> > > 
> > > 使用上述代码可以拿到当前机器，连接网络的IP，不会造成拿错地址的情况，在有虚拟网卡的测试环境下测试。
> > 
> > 
> > 8.8.8.8是公网地址，在不连外网情况下，不行吧。 很多公司的服务器都是不给连外网的。
> 
> 因为用的UDP，所以不会真去连接到外网的，即使连接不到外网也可以的。

试了一下，真的可以，所以那个地址随便输入一个，也是可以的

**Comment by liyue201** [comment]
@younglifestyle 你提个pr吧

**Comment by younglifestyle** [comment]
> @younglifestyle 你提个pr吧

已提交
