### ISSUE TITLE
Hope to add gin and xorm support and examples

### ISSUE THREAD

**Issue by emmeair** [douyu/jupiter#160]

**Comment by younglifestyle** [comment]
gin is supported

**Comment by emmeair** [comment]
> gin is supported

I just looked through the code and found an example, thank you, and the result returned by gorm makes me use it uncomfortably, if I can support xorm, I would be very grateful,Or make it easier to inject components into jupiter

**Comment by mlboy** [comment]
there is an example 

https://github.com/douyu/jupiter/blob/master/example/http/gin/main.go

**Comment by younglifestyle** [comment]
> > gin is supported
> 
> I just looked through the code and found an example, thank you, and the result returned by gorm makes me use it uncomfortably, if I can support xorm, I would be very grateful,Or make it easier to inject components into jupiter

we have no plans to add other orm at the moment, and welcome your pr :)

**Comment by emmeair** [comment]
> > > gin is supported
> > 
> > 
> > I just looked through the code and found an example, thank you, and the result returned by gorm makes me use it uncomfortably, if I can support xorm, I would be very grateful,Or make it easier to inject components into jupiter
> 
> we have no plans to add other orm at the moment, and welcome your pr :)

Soon, I will try to write code to adapt to jupiter. If there is no problem, I will pr
