### ISSUE TITLE
[BUG] 官方代码中-example->grpc->etcd-client中的main.go中56行报错：etcdv3.StdConfig

### ISSUE THREAD

**Issue by cw2018** [douyu/jupiter#171]
## Issue Description

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by mlboy** [comment]
具体错误可以贴一下吗?
