### ISSUE TITLE
[BUG] jupiter tool 中某方法 书写重复for

### ISSUE THREAD

**Issue by mlboy** [douyu/jupiter#173]
## Issue Description

Type: *bug report*

### Describe what happened
重复代码for

https://github.com/douyu/jupiter/blob/4b13cd1442ad83ab6b08c38f7f9277f8dc72dd0a/tools/jupiter/common/util.go#L15-L33

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by Alex1996a** [comment]
https://github.com/douyu/jupiter/pull/174
