### ISSUE TITLE
[BUG] 文档更新，并没有使用redigo，你们用的go-redis

### ISSUE THREAD

**Issue by 741369** [douyu/jupiter#18]
![image](https://user-images.githubusercontent.com/13210977/83481548-ad8be200-a4d0-11ea-8ac9-d3dac8a9c521.png)

**Comment by gorexlv** [comment]
感谢您的建议。这里是我们内部基于redigo实现的描述，文档描述不准确，会尽快去掉。
我们内部的基于redigo的增强实现相对go-redis功能更多，目前还未整理出来。因原redigo的维护现状，我们不确定是否要释放这部分功能，期待您的建议。

**Comment by MEX7** [comment]
文档说明已更正
