### ISSUE TITLE
微信群，好像过期了，是否可以更新？ 

### ISSUE THREAD

**Issue by hackfengJam** [douyu/jupiter#182]
如题！

正在研究Go的相关微服务框架，想加入社群，了解更多。

希望能及时更新微信二维码，谢谢！

**Comment by younglifestyle** [comment]
@MEX7

**Comment by tanjiancheng** [comment]
+1

**Comment by MEX7** [comment]
ok
在 2020年9月10日 +0800 AM10:37，ctam <notifications@github.com>，写道：

**Comment by lpf2015** [comment]
都过期，好多天了
