### ISSUE TITLE
关于grpc服务注册的server-name问题

### ISSUE THREAD

**Issue by tanjiancheng** [douyu/jupiter#184]
// 2. 通过resolver获取服务器地址
func dialServer() {
    config := grpc.DefaultConfig()
    config = config.WithDialOption()
    config.Address = "etcd:///server-name" // 注意必须填写etcd:///
    client := helloworld.NewGreeterClient(config.Build())
    rep, err := client.SayHello(context.Background(), &helloworld.HelloRequest{
        Name: "hi",
    })
}

我看客户端通过
  config.Address = "etcd:///server-name"
获取对应的grpc服务端信息，请问下服务端那边怎么指定这个server-name，我没有找到相关例子

**Comment by hcclinux** [comment]
你指的server-name，在生成xxx.pb.go里面就已经有了

**Comment by tanjiancheng** [comment]
@hcclinux 我根据example里面的grpc/etcd-server 启动后注册进etcd里面的信息如下
![image](https://user-images.githubusercontent.com/7401570/92838855-ddbd1800-f411-11ea-9130-1ef887a5a63d.png)
并没有看到对应的服务名称，感觉都是main

**Comment by liyue201** [comment]
西山居 也用go吗 @tanjiancheng

**Comment by liyue201** [comment]
这个确实没有指定server-name的地方， 只有一处默认配置

```

func defaultServiceInfo() ServiceInfo {
	si := ServiceInfo{
		Name:       pkg.Name(),
		AppID:      pkg.AppID(),
		Weight:     100,
		Enable:     true,
		Healthy:    true,
		Metadata:   make(map[string]string),
		Region:     pkg.AppRegion(),
		Zone:       pkg.AppZone(),
		Kind:       0,
		Deployment: "",
		Group:      "",
	}
	si.Metadata["appMode"] = pkg.AppMode()
	si.Metadata["appHost"] = pkg.AppHost()
	si.Metadata["startTime"] = pkg.StartTime()
	si.Metadata["buildTime"] = pkg.BuildTime()
	si.Metadata["appVersion"] = pkg.AppVersion()
	si.Metadata["jupiterVersion"] = pkg.JupiterVersion()
	return si
}
```

**Comment by tanjiancheng** [comment]
@liyue201 西山居有用go的，现在明白了，这块最好例子里面也体现一下

**Comment by cute-angelia** [comment]
server := xgrpc.StdConfig("grpc").Build()
server.Info().Name = "your server name"



这么写， 还是 main ...
