### ISSUE TITLE
jupiter tools

### ISSUE THREAD

**Issue by lpf2015** [douyu/jupiter#185]
## Issue Description
go/src/github.com/douyu/jupiter/tools/jupiter/new/tools.go:34:8: invalid argument newArgs (type cli.Args) for len
go/src/github.com/douyu/jupiter/tools/jupiter/new/tools.go:39:10: invalid operation: name == "" (mismatched types cli.Args and string)
go/src/github.com/douyu/jupiter/tools/jupiter/new/tools.go:42:16: cannot use name (type cli.Args) as type string in assignment
Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by lpf2015** [comment]
[root@localhost ~]# go version
go version go1.11.5 linux/amd64

**Comment by MEX7** [comment]
需要再`tools/jupiter`这个目录下执行
> go mod vendor

下载相关依赖
