### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lpf2015** [douyu/jupiter#187]
## Issue Description

Type: *bug report*

### Describe what happened
api POST 获取不到数据，或者提供个例子

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by lpf2015** [comment]
哎，为什么没有人回答呢。还是有其他地方提问，感觉这个框架，更新太慢

**Comment by mlboy** [comment]
web 使用的是gin 还是echo？

**Comment by MEX7** [comment]
Considering that there is no reply for a long time, close this issue first, if you still have any questions, please feel free to reopen it.
