### ISSUE TITLE
[BUG] 执行 go get -u github.com/douyu/jupiter/tools/jupiter 报错

### ISSUE THREAD

**Issue by daydaygo** [douyu/jupiter#19]
## Issue Description

Type: *bug report*

### Describe what happened

```
➜ tmp go get -u github.com/douyu/jupiter/tools/jupiter
# github.com/douyu/jupiter/tools/jupiter/new
../../../go/src/github.com/douyu/jupiter/tools/jupiter/new/tools.go:35:8: invalid argument newArgs (type cli.Args) for len
../../../go/src/github.com/douyu/jupiter/tools/jupiter/new/tools.go:39:17: invalid operation: newArgs[0] (type cli.Args does not support indexing)
```

### Describe what you expected to happen

执行完 `go get -u github.com/douyu/jupiter/tools/jupiter` 后 `jupiter` 命令可用

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by askuy** [comment]
使用golang 1.13，启用go mod后，使用 go get。
