### ISSUE TITLE
must specify golang version >= 13, or will fail in helloworld example

### ISSUE THREAD

**Issue by moooofly** [douyu/jupiter#194]
## Issue Description

Type: *bug report*

### Describe what happened

```
[#1#root@ubuntu-dev ~]$go version
go version go1.12.17 linux/amd64
```

```
[#19#root@ubuntu-dev /go/src/github.com/douyu/jupiter/example/helloworld]$go run main.go 
# github.com/douyu/jupiter/pkg/flag
../../pkg/flag/flag.go:39:2: undefined: testing.Init
[#20#root@ubuntu-dev /go/src/github.com/douyu/jupiter/example/helloworld]$
```

### Describe what you expected to happen

as described by http://jupiter.douyu.com/jupiter/1.1quickstart.html

### How to reproduce it (as minimally and precisely as possible)

as above

#### What version of Go are you using (`go version`)?

```
[#1#root@ubuntu-dev ~]$go version
go version go1.12.17 linux/amd64
```

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
[#2#root@ubuntu-dev ~]$go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072143272=/tmp/go-build -gno-record-gcc-switches"
[#3#root@ubuntu-dev ~]$

</pre></details>

### Anything else we need to know?

when upgrading golang version to go version go1.13.15 linux/amd64, everything is ok.

**Comment by MEX7** [comment]
在`flag`中调用了一个`go1.13`新增的`testing.Init()`方法，这边在讨论是否需要再初始化的时候进行调用。

**Comment by MEX7** [comment]
在 https://github.com/douyu/jupiter/commit/583249fbac4a00deed465bdd4767ac98d1e0c89f 提交中，移除了`testing.Init`的调用。
