### ISSUE TITLE
fail in helloworld example as alibaba/sentinel-golang has changed something

### ISSUE THREAD

**Issue by moooofly** [douyu/jupiter#195]
## Issue Description

Type: *bug report*

### Describe what happened

```
[#44#root@ubuntu-dev /go/src/github.com/douyu/jupiter/example/helloworld]$go run main.go              
# github.com/douyu/jupiter/pkg/sentinel
../../pkg/sentinel/config.go:48:19: undefined: flow.FlowRule
[#45#root@ubuntu-dev /go/src/github.com/douyu/jupiter/example/helloworld]$
```

### Describe what you expected to happen

as described by http://jupiter.douyu.com/jupiter/1.1quickstart.html

### How to reproduce it (as minimally and precisely as possible)

as above

#### What version of Go are you using (`go version`)?

<pre>
[#3#root@ubuntu-dev ~]$go version
go version go1.13.15 linux/amd64
[#4#root@ubuntu-dev ~]$

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
[#2#root@ubuntu-dev ~]$go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build072143272=/tmp/go-build -gno-record-gcc-switches"
[#3#root@ubuntu-dev ~]$

</pre></details>

### Anything else we need to know?

as https://github.com/alibaba/sentinel-golang/commit/a9fa3001c12fcebf037fec0cd81f001fa62f99f4 described

> Rename flow.FlowRule to flow.Rule and remove unused fields

**Comment by MEX7** [comment]
目前采用的是`github.com/alibaba/sentinel-golang v0.6.0`，等`v1.0.0-M1`正式发布后，jupiter会进行相关更新。

**Comment by MEX7** [comment]
Considering that there is no reply for a long time, close this issue first, if you still have any questions, please feel free to reopen it.
