### ISSUE TITLE
中文文档中的链接内容不存在

### ISSUE THREAD

**Issue by moooofly** [douyu/jupiter#196]
## Issue Description

Type: *bug report*

### Describe what happened

在《[2.1.2 查看版本信息](http://jupiter.douyu.com/jupiter/2.1startup.html#_2-1-1-%E5%90%AF%E5%8A%A8%E6%96%B9%E5%BC%8F)》中，有

> Jupiter参考了istio的[编译工具](https://github.com/douyu/jupiter/tree/master/tool/build.sh)，可以将应用的版本信息、编译时间...

而这个链接和对应的文件在项目中根本就搜不到

### Describe what you expected to happen

麻烦文档更新一下啊，既然开源，总归要好好弄才能得到别人的支持嘛

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by moooofly** [comment]
这么多天，都没人回复啊

**Comment by MEX7** [comment]
目前已修复，文档和脚本都已经更新。
