### ISSUE TITLE
[BUG] 新版本发布，文档没有同步更新吗？

### ISSUE THREAD

**Issue by cw2018** [douyu/jupiter#202]
## Issue Description

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by MEX7** [comment]
目前Jupiter改动不大，文档基本和之前的内容一致，具体是那部分内容，我这边进行完善。
