### ISSUE TITLE
[BUG]中文简介页面排版问题

### ISSUE THREAD

**Issue by xuchaojie** [douyu/jupiter#21]
## Issue Description

Type: *bug report*

### Describe what happened

![image](https://user-images.githubusercontent.com/32586927/83607431-d03ff880-a5ad-11ea-8d41-3b2c49ac5571.png)

这里应该是无序列表的第一项吧，按照[issue#15](https://github.com/douyu/jupiter/issues/15)中的方式没能提`pr`，只好新建一个`issue`。

**Comment by MEX7** [comment]
感谢勘误，已修正。
