### ISSUE TITLE
请教一个grpc客户端池化的问题

### ISSUE THREAD

**Issue by luyongjuan** [douyu/jupiter#211]
请问大佬 为什么没有使用grpc client pool，没有对客户端的连接进行池化操作呢？直接暴露grpc client 的原始结构，业务方使用的时候可能会出错，导致连接泄漏。这些问题当前项目是怎么考虑的呢？

**Comment by Owen-Zhang** [comment]
grpc 传输是在http2的基础上的， http2本来就只需要一个tcp链接
