### ISSUE TITLE
etcd注册中心是否要加上重连机制

### ISSUE THREAD

**Issue by Owen-Zhang** [douyu/jupiter#214]
按现在代码的意思如果service挂了，重新启动没有问题，但有些情况下网络不稳定断网了，但程序还是在正常运行(只是连接不到注册中心), 过了ttl时间后，注册中心会将此节点path删除(正常), 但又过了一会网络好了，此时service就不会自动注册到中心了，相当于它是一个孤儿。

**Comment by cute-angelia** [comment]
。。。。不活跃， 害怕没人维护啊

**Comment by askuy** [comment]
> 。。。。不活跃， 害怕没人维护啊
有邮箱吗，可以交流

**Comment by askuy** [comment]
> 。。。。不活跃， 害怕没人维护啊

有邮箱吗，可以交流
