### ISSUE TITLE
will it support loading config from etcd for gorm

### ISSUE THREAD

**Issue by gavinyjliang** [douyu/jupiter#223]
## Issue Description

Type: *feature request*

**Comment by gavinyjliang** [comment]
Currently, it seems gorm does not support loading config from etcd. Will any plan to support this?

**Comment by sylarXu** [comment]
Juno save config raw data in etcd right now，
you can get more detail in [ 配置中心设计](http://jupiter.douyu.com/juno/3.3design.html#_3-3-1-%E5%85%B3%E9%94%AE%E6%A6%82%E5%BF%B5)；
And juno-agent contains a implement for loading config from ETCD;
By the way, we will do something more in k8s, like load config from k8s configMap；
