### ISSUE TITLE
hookSignals func,these two places can be combined into a case,Sleep paused for 3s, in fact, you can use the Context cancel mechanism here.

### ISSUE THREAD

**Issue by daheige** [douyu/jupiter#24]
https://github.com/douyu/jupiter/blob/25486432a0af6f6c3d90609d01cdacf145dc544b/signal_linux.go#L46
https://github.com/douyu/jupiter/blob/25486432a0af6f6c3d90609d01cdacf145dc544b/signal_linux.go#L50
These two places can be combined into one case. In this for, semaphore monitoring is performed. Although an independent goroutine+for is continuously opened to ask whether the semaphore is monitored, it uses a very time method. Sleep paused for 3s, in fact, you can use the Context cancel mechanism here. There is another bad point here. Since the smooth exit is done, how do you know that it is paused for 3s? I think that the smooth exit should be done through the context ctx mechanism or through the channel, or you can just wait for the context ctx to timeout and exit. Are better than direct time.Sleep 3s

**Comment by daheige** [comment]
time.Sleep pause mode is really a very poke, very bad design, it is not recommended to use this

**Comment by gorexlv** [comment]
Thank you for pointing that out.

1. Actually, we classifiy system signals to three cases:
     - case1: "forced stop"
     - case2: "graceful stop"
     - case3: "graceful restart".
 For some reason, 'graceful restart' function haven't release yet,  so use `Stop` instead here.

2. 'Stop for 3 seconds, just to prevent signal reentry, no other meaning. In other words, this does not affect the normal exit or grafully stop.

Thanks for your job. Contribution is welcome :)

**Comment by daheige** [comment]
You still haven’t answered why this is a pause of 3s. This is your assumption, or the result of the project’s practice. This is a very poke, very bad design. This is a very rough writing. I suggest you look at the context cancel mechanism. , Or use done chan struct{} to notify a true smooth exit, rather than such a brutal design.

**Comment by gorexlv** [comment]
> You still haven’t answered why this is a pause of 3s. This is your assumption, or the result of the project’s practice. This is a very poke, very bad design. This is a very rough writing. I suggest you look at the context cancel mechanism. , Or use done chan struct{} to notify a true smooth exit, rather than such a brutal design.

Thank you for your suggestion. As I explained, it's for preventing signal reentry, and is no need to precisely control the exit here. At the same time, I basically agree with your opinions about signal synchronization and hope that we can make some improvements together.

Allow me to clarify that I'm just explaining why it's used that way, not ruling out the possibility of using channel mechanism. 

Thanks for your job.

**Comment by gorexlv** [comment]
I'll close it, please reopen it If there are any questions.

Thanks!
