### ISSUE TITLE
[BUG] fix all test error

### ISSUE THREAD

**Issue by hnlq715** [douyu/jupiter#250]
## Issue Description

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by gorexlv** [comment]
close
