### ISSUE TITLE
[BUG]执行   go get -u github.com/douyu/jupiter/cmd/jupiter 出错

### ISSUE THREAD

**Issue by ytd7777** [douyu/jupiter#258]
## Issue Description

执行   go get -u github.com/douyu/jupiter/cmd/jupiter 
报下面的错：

github.com/douyu/jupiter/cmd/jupiter: ambiguous import: found package github.com/douyu/jupiter/cmd/jupiter in multiple modules:
        github.com/douyu/jupiter v0.3.2 (D:\Go\GoPath\pkg\mod\github.com\douyu\jupiter@v0.3.2\cmd\jupiter)
        github.com/douyu/jupiter/cmd/jupiter v0.0.0-20210716055700-612e8e9696ae (D:\Go\GoPath\pkg\mod\github.com\douyu\jupiter\cmd\jupiter@v0.0.0-20210716055700-612e8e9696ae)

#### What version of Go are you using (`go version`)?

<pre>
1.16.4

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ytd7777** [comment]
这个项目没人维护了么？

**Comment by ytd7777** [comment]
斗鱼那大一个公司？？

**Comment by hnlq715** [comment]
@ytd7777 麻烦贴一下go env的输出看看，我这边运行是好的 ：）

**Comment by ytd7777** [comment]
@hnlq715 好了

**Comment by hnlq715** [comment]
ok
