### ISSUE TITLE
bytes.Buffer for some long string or byte concatenation, it can indeed improve performance, but don’t forget that this will open up a space of const smallBufferSize = 64 size

### ISSUE THREAD

**Issue by daheige** [douyu/jupiter#26]
https://github.com/douyu/jupiter/blob/25486432a0af6f6c3d90609d01cdacf145dc544b/pkg/ecode/status.go#L72

bytes.Buffer for some long string or byte concatenation, it can indeed improve performance, but don’t forget that this will open up a space of const smallBufferSize = 64 size, I found that many of your code in golang are written like this, if for comparison A small amount of splicing, please do not open up so much space, this is a waste, it is better to use slice append+strings.Join to complete, please do not write some more poke code, please

**Comment by gorexlv** [comment]
Good advice, especially on performance comparisons. 

Thanks for your job, Contribution is welcome :)

**Comment by daheige** [comment]
string stitching

     In the case of existing string arrays, using strings.Join() can have better performance. In some occasions with higher performance requirements, try to use buffer.WriteString() to get better performance. , Use the operator directly, the code is shorter and clearer, and you can get better readability. If you need to concatenate not only strings, but also other needs such as numbers, you can consider fmt.Sprintf()

**Comment by gorexlv** [comment]
thanks for you jobs :)
