### ISSUE TITLE
example 跑不起来[BUG]

### ISSUE THREAD

**Issue by cool-cold** [douyu/jupiter#269]
## Issue Description

我下载了最新的jupiter然后尝试运行文档中提供的[helloworld示例](https://jupiter.douyu.com/jupiter/1.1quickstart.html)

### Describe what happened
期望能正常跑起来

### Describe what you expected to happen

<pre>
❯ go run main.go
../../../go/pkg/mod/github.com/coreos/etcd@v3.3.22+incompatible/clientv3/client.go:35:2: missing go.sum entry for module providing package github.com/google/uuid (imported by github.com/coreos/etcd/clientv3); to add:
        go get github.com/coreos/etcd/clientv3@v3.3.22+incompatible
../../../go/pkg/mod/github.com/douyu/jupiter@v0.3.3/pkg/util/xgo/parallel.go:20:2: missing go.sum entry for module providing package golang.org/x/sync/errgroup (imported by github.com/douyu/jupiter/pkg/application); to add:
        go get github.com/douyu/jupiter/pkg/application@v0.3.3

</pre>
### How to reproduce it (as minimally and precisely as possible)

1.  通过 go mod tidy 整理依赖之后报以下错误
<pre>
❯ go mod tidy
go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
go: finding module for package google.golang.org/grpc/naming
go: finding module for package github.com/HdrHistogram/hdrhistogram-go
go: downloading google.golang.org/grpc/examples v0.0.0-20211015201449-4757d0249e2d
go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20211015201449-4757d0249e2d
go: found github.com/HdrHistogram/hdrhistogram-go in github.com/HdrHistogram/hdrhistogram-go v1.1.2
go: finding module for package google.golang.org/grpc/naming
jupiter-demo imports
        github.com/douyu/jupiter imports
        github.com/douyu/jupiter/pkg/application imports
        github.com/douyu/jupiter/pkg/registry/etcdv3 imports
        github.com/coreos/etcd/clientv3 tested by
        github.com/coreos/etcd/clientv3.test imports
        github.com/coreos/etcd/integration imports
        github.com/coreos/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.41.0), but does not contain package google.golang.org/grpc/naming

</pre>
### Tell us your environment
```shell
❯ Jupiter --version
jupiter version 0.1.0

```
#### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 darwin/amd64

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/sy/go/bin"
GOCACHE="/Users/sy/Library/Caches/go-build"
GOENV="/Users/sy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-ldflags=-compressdwarf=false"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sy/WorkSpace/go/jupiter-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cr/rj6pwfv14q9986x15zvx0pp80000gn/T/go-build1831090279=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by hnlq715** [comment]
建议直接跑example目录中的代码示例

**Comment by 1000172** [comment]
> ## Issue Description
> 我下载了最新的jupiter然后尝试运行文档中提供的[helloworld示例](https://jupiter.douyu.com/jupiter/1.1quickstart.html)
> 
> ### Describe what happened
> 期望能正常跑起来
> 
> ### Describe what you expected to happen
> ❯ go run main.go
> ../../../go/pkg/mod/github.com/coreos/etcd@v3.3.22+incompatible/clientv3/client.go:35:2: missing go.sum entry for module providing package github.com/google/uuid (imported by github.com/coreos/etcd/clientv3); to add:
>         go get github.com/coreos/etcd/clientv3@v3.3.22+incompatible
> ../../../go/pkg/mod/github.com/douyu/jupiter@v0.3.3/pkg/util/xgo/parallel.go:20:2: missing go.sum entry for module providing package golang.org/x/sync/errgroup (imported by github.com/douyu/jupiter/pkg/application); to add:
>         go get github.com/douyu/jupiter/pkg/application@v0.3.3
> 
> ### How to reproduce it (as minimally and precisely as possible)
> 1. 通过 go mod tidy 整理依赖之后报以下错误
> 
> ❯ go mod tidy
> go: finding module for package google.golang.org/grpc/examples/helloworld/helloworld
> go: finding module for package google.golang.org/grpc/naming
> go: finding module for package github.com/HdrHistogram/hdrhistogram-go
> go: downloading google.golang.org/grpc/examples v0.0.0-20211015201449-4757d0249e2d
> go: found google.golang.org/grpc/examples/helloworld/helloworld in google.golang.org/grpc/examples v0.0.0-20211015201449-4757d0249e2d
> go: found github.com/HdrHistogram/hdrhistogram-go in github.com/HdrHistogram/hdrhistogram-go v1.1.2
> go: finding module for package google.golang.org/grpc/naming
> jupiter-demo imports
>         github.com/douyu/jupiter imports
>         github.com/douyu/jupiter/pkg/application imports
>         github.com/douyu/jupiter/pkg/registry/etcdv3 imports
>         github.com/coreos/etcd/clientv3 tested by
>         github.com/coreos/etcd/clientv3.test imports
>         github.com/coreos/etcd/integration imports
>         github.com/coreos/etcd/proxy/grpcproxy imports
>         google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.41.0), but does not contain package google.golang.org/grpc/naming
> 
> ### Tell us your environment
> ```shell
> ❯ Jupiter --version
> jupiter version 0.1.0
> ```
> 
> #### What version of Go are you using (`go version`)?
> $ go version
> go version go1.17.1 darwin/amd64
> 
> #### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> 
> $ go env
> GO111MODULE="on"
> GOARCH="amd64"
> GOBIN="/Users/sy/go/bin"
> GOCACHE="/Users/sy/Library/Caches/go-build"
> GOENV="/Users/sy/Library/Application Support/go/env"
> GOEXE=""
> GOEXPERIMENT=""
> GOFLAGS="-ldflags=-compressdwarf=false"
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOINSECURE=""
> GOMODCACHE="/Users/sy/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="darwin"
> GOPATH="/Users/sy/go"
> GOPRIVATE=""
> GOPROXY="https://goproxy.cn,direct"
> GOROOT="/usr/local/opt/go/libexec"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
> GOVCS=""
> GOVERSION="go1.17.1"
> GCCGO="gccgo"
> AR="ar"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/Users/sy/WorkSpace/go/jupiter-demo/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cr/rj6pwfv14q9986x15zvx0pp80000gn/T/go-build1831090279=/tmp/go-build -gno-record-gcc-switches -fno-common"
> ### Anything else we need to know?
我试了在mod中加入replace google.golang.org/grpc => google.golang.org/grpc v1.26.0这条，可以获取到包了，你可以试试

**Comment by hnlq715** [comment]
先关闭此issue，还有问题可以重开
