### ISSUE TITLE
[BUG]使用balance:grpc.round_robin或jupiter.p2c，使用服务发现必然出现panic问题

### ISSUE THREAD

**Issue by kiqi007** [douyu/jupiter#293]
## Issue Description
使用balance:grpc.round_robin或jupiter.p2c，使用服务发现必然出现panic问题

### panic堆栈信息：
panic: runtime error: comparing uncomparable type server.ServiceInfo
goroutine 62 [running]:
google.golang.org/grpc/attributes.(*Attributes).Equal(0x14000248260, 0x14000248260, 0x17)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/attributes/attributes.go:93 +0x154
google.golang.org/grpc/resolver.addressMapEntryList.find(0x14000248280, 0x1, 0x1, 0x14000138210, 0x12, 0x14000042308, 0x17, 0x14000248260, 0x0, 0x0, ...)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/resolver/map.go:49 +0x78
google.golang.org/grpc/resolver.(*AddressMap).Get(0x14000248270, 0x14000138210, 0x12, 0x14000042308, 0x17, 0x14000248260, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/resolver/map.go:59 +0x8c
google.golang.org/grpc/balancer/base.(*baseBalancer).regeneratePicker(0x14000235480)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/balancer/base/balancer.go:167 +0xcc
google.golang.org/grpc/balancer/base.(*baseBalancer).UpdateSubConnState(0x14000235480, 0x105314a80, 0x140004459c0, 0x2, 0x0, 0x0)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/balancer/base/balancer.go:219 +0x18c
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0x14000266e60)
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/balancer_conn_wrappers.go:86 +0x69c
created by google.golang.org/grpc.newCCBalancerWrapper
        /Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/balancer_conn_wrappers.go:67 +0x184
### panic调试信息：
/Users/cengqi/workspace/go/pkg/mod/google.golang.org/grpc@v1.43.0/attributes:93
![image](https://user-images.githubusercontent.com/81557994/155667822-17174073-1d0e-40dc-9fb3-bcb1f0eca8d1.png)

### 此段attributes写入位置：
/Users/cengqi/workspace/go/pkg/mod/github.com/douyu/jupiter@v0.3.5/pkg/client/grpc/resolver:63
![image](https://user-images.githubusercontent.com/81557994/155667932-2da8da45-eee0-4e43-ae1b-d4c44e4d7013.png)

### 问题原因：
grpc新版本修改了base.balance的逻辑，对于address的是否相等的判断，加入了对attribute的判断(因此attribute需实现equal接口或允许等值匹配)，但resolver中写入的servicInfo未实现equal接口，且无法等值比较。

### 修复方案建议：
serviceInfo增加equal接口实现

**Comment by hnlq715** [comment]
@kiqi007 请尝试下v0.4.3

https://github.com/douyu/jupiter/releases/tag/v0.4.3
