### ISSUE TITLE
服务启动时报 can't make directories for new logfile错误

### ISSUE THREAD

**Issue by zhengyansheng** [douyu/jupiter#308]
## go version
✗ go version
go version go1.16.8 darwin/amd64

## os 
Mac

## 背景
我没有用jupiter自带的xlog，因为我想要保存到日志文件中的日志是按行的而不是json
因此我在代码中自定义了log 使用go.uber.org/zap， 这个使用是没有问题的；

## 错误描述
服务在启动的时候，抱日志错误，支持提示，但是不影响服务启动
2022-03-26 11:04:50.552458 +0800 CST m=+21.008511193 write error: can't make directories for new logfile: mkdir /home/www: operation not supported

我debug判断是它引起的
https://github.com/douyu/jupiter/blob/master/pkg/xlog/rotate/lumberjack_darwin.go#L300

但是无论我在配置文件中如何定义，它都不起作用。
```
[jupiter.logger.default]
debug = false         # 是否在命令行输出
enableConsole = false # 是否按命令行格式输出
name = "default.json" # 日志名称
dir = "/tmp/logs"             # 日志路径
async = true          # 默认异步采集日志
```

请求你的帮助，我如何禁止这个报错的输出

**Comment by hnlq715** [comment]
感谢反馈，我找时间排查下这个问题

**Comment by hnlq715** [comment]
@zhengyansheng 我这边尝试跑了下，并没有复现，麻烦方便的时候提供下最小复现代码块，我这边再看看，多谢

**Comment by hnlq715** [comment]
@zhengyansheng 我确认了下，你这个配置文件是必须引入xlog才会生效，所以还是建议不要自己封装log，如果有特殊需求可以提出来，在框架支持即可 ：）

**Comment by hnlq715** [comment]
如果还有问题，欢迎重新打开此issue

**Comment by hnlq715** [comment]
如果还有问题，欢迎重新打开此issue
