### ISSUE TITLE
[BUG] jupiter模板项目编译问题

### ISSUE THREAD

**Issue by Cynicism-zx** [douyu/jupiter#316]
jupiter new demo 后进入项目不做任何操作,即会出现如图错误
![2022-04-21](https://user-images.githubusercontent.com/54843425/164387852-9bbc9b31-1640-4dbb-bc8a-0fb29a07137c.png)

**Comment by hnlq715** [comment]
感谢反馈，欢迎提PR @lwj-Cynicism 🙂

**Comment by lwj-Cynicism** [comment]
> 感谢反馈，欢迎提PR @lwj-Cynicism slightly_smiling_face

貌似是没有提pr权限的样子 @hnlq715

**Comment by hnlq715** [comment]
可以先fork自己的repo并提交改动，然后再发起PR到这个repo

**Comment by hnlq715** [comment]
#317 模板已重构，欢迎体验

https://github.com/douyu/jupiter-layout
