### ISSUE TITLE
feat(demo): 实现通用的服务

### ISSUE THREAD

**Issue by hnlq715** [douyu/jupiter#332]
## Issue Description

Type: *feature request*

### Describe what feature you want

基于jupiter项目模板
https://github.com/douyu/jupiter-layout

- [ ] 发号器
  - https://github.com/bwmarrin/snowflake
  - https://github.com/speps/go-hashids
- [ ] 短网址
  - redis
  - 发号器

**Comment by ywanbing** [comment]
现在已经用过新的模板实现 发号器，在实现过程中，发现模板的 grpc 服务并没有注册上。
我在`example/uuid/internal/uuidserver/server/server.go` 的 `initApp` 手动注册了
对新模板 缺少一个开发的具体流程。
