### ISSUE TITLE
[BUG]2.2.3 远端配置

### ISSUE THREAD

**Issue by wuxiangege** [douyu/jupiter#374]
## Issue Description

Type: *bug report*

### Describe what happened
I don't open many pages,for example 通过远端配置读取单行配置示例 and so on

### Describe what you expected to happen
normal access

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

#### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

#### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by hnlq715** [comment]
fixed
