### ISSUE TITLE
mac go 1.19 下面报错了

### ISSUE THREAD

**Issue by busyfree** [douyu/jupiter#377]
golang.org/x/sys 这个依赖库版本低了

❯ GOPROXY=https://goproxy.cn/,direct go install github.com/douyu/jupiter/tools/jupiter@latest
# golang.org/x/sys/unix
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../../../libs/pkg/mod/golang.org/x/sys@v0.0.0-20200805065543-0cf7623e9dbd/unix/zsyscall_darwin_amd64.go:121:3: too many errors

**Comment by hnlq715** [comment]
@busyfree 看上去你安装的命令不对，试下这个呢？

GOPROXY=https://goproxy.cn/,direct go install github.com/douyu/jupiter/cmd/jupiter@latest

**Comment by busyfree** [comment]
上面的命令是从文档复制的，那就是文档过时了。下面这个新的也是不行

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/504251/187362171-f2b72e04-9b47-401e-aaa5-59248f42799b.png">

**Comment by hnlq715** [comment]
我这边看上去没办法重现

**Comment by hnlq715** [comment]
我在github actions上增加了windows和macos的构建，目前看都是正常的，你可以看看是不是本地环境的问题呢

先关闭了，有问题欢迎再打开

**Comment by y1wenZhang** [comment]
这个问题解决了吗，我本地也有这个问题

**Comment by hnlq715** [comment]
@y1wenZhang 麻烦提供具体的错误信息，github上有跑macos的ci，暂时没发现问题

**Comment by FanGaoXS** [comment]
这个问题我解决了， 我是将我的GOPROXY设置为`https://mirrors.aliyun.com/goproxy/,direct`，简而言之就是要加上aliyun这个镜像，供参考。
参考自：https://github.com/douyu/jupiter/tree/master/cmd/jupiter
