### ISSUE TITLE
不支持熔断

### ISSUE THREAD

**Issue by liyue201** [douyu/jupiter#40]
希望能支持熔断和服务降级

**Comment by gorexlv** [comment]
正在接入sentinel-golang, 验证稳定以后，会分享出来。

**Comment by gorexlv** [comment]
#37

**Comment by gorexlv** [comment]
Currently supports flow control.
Circutbreak, downgrade and system control will be supported after sentinel v0.5.0 released.

**Comment by lycclsltt** [comment]
为啥文档里些的支持呢？

**Comment by lycclsltt** [comment]
为啥文档里写的支持呢
