### ISSUE TITLE
如何去掉日志打印中的默认Fields

### ISSUE THREAD

**Issue by jyelee** [douyu/jupiter#417]
## Issue Description

使用xlog StdConfig 初始化的logger打印日志的时候会默认带上aid, iid两个field, 这个如何通过配置的方式去掉那？

Type: *feature request*

**Comment by jyelee** [comment]
好的，这个能通过配置的方式去掉吗，试了下没试出来，所以提个问题请教下

**Comment by hnlq715** [comment]
目前不支持 :-)
