### ISSUE TITLE
[BUG]主动断开( ctrl + c)  http server 控制台会报错

### ISSUE THREAD

**Issue by ycjiafei** [douyu/jupiter#46]
## Issue Description

主动断开( ctrl + c)  http server 控制台会报错

### Describe what happened
运行的是 example/http/gin/main.go
```
go run main.go --config=config.toml
```
![image](https://user-images.githubusercontent.com/19790443/84772531-a525c200-b00d-11ea-9e91-b8408f1e704f.png)

**Comment by mlboy** [comment]
这不是报错。 你看你main文件，例子中把err  panic 了

**Comment by gorexlv** [comment]
退出的错误信息显示不太友好，可以优化一下体验

**Comment by mlboy** [comment]
> 退出的错误信息显示不太友好，可以优化一下体验

现在 gin 的example 和 echo 的example 是保持一致的

https://github.com/douyu/jupiter/blob/master/example/http/simple/main.go#L27
https://github.com/douyu/jupiter/blob/master/example/http/gin/main.go#L27

我来调整一下 

```
//把
xlog.Panic(err.Error())
//调整为：
xlog.Error(err.Error())
```
形成如下提示：

![image](https://user-images.githubusercontent.com/1733903/84803682-e54c6b00-b034-11ea-9914-f67e489fc056.png)

**Comment by gorexlv** [comment]
@mlboy 我的想法是识别Server Closed错误，然后结合上下文优化一下抛错误的体验。
有些发布、监控系统会监听错误输出和退出码，Error/Panic的方式都不优雅。

**Comment by qiujiafei123** [comment]
> 退出的错误信息显示不太友好，可以优化一下体验

没注意看 gin 例子中的是 xlog.panic ，以为是退出的某个环节内部 panic 了， 这个是调用方主动将 err panic 了， 那这个报错也正常， 我的锅 😭    
还有一个小问题， 主动关闭的时候会打印两次 `INFO exit server`
![image](https://user-images.githubusercontent.com/19790443/84846776-1901b200-b082-11ea-9143-127145a9b714.png)

**Comment by mlboy** [comment]
> @mlboy 我的想法是识别Server Closed错误，然后结合上下文优化一下抛错误的体验。
> 有些发布、监控系统会监听错误输出和退出码，Error/Panic的方式都不优雅。
> 
> [2d1b7c2](https://github.com/douyu/jupiter/commit/2d1b7c26aa2f3fcce825513702a029a9da6bac4b) 简单的屏蔽了ServerClosed/ServerStop错误。后面考虑更优雅的方案

嗯，另外有个问题就是：非主动退出时，无法感知server close行为。服务常态是一直运行，在退出时候能感知到服务的状态变化。即使，在主动关闭时，也多收到一个警告。
