### ISSUE TITLE
工程目录对swagger不友好的问题

### ISSUE THREAD

**Issue by feixiao** [douyu/jupiter#56]
目前自动生成的目录工程main.go在demo/cmd下面，这种情况下面我执行swag init的时候无法自动化生成文档，我将main.go移动到demo目录下面即可，使用的框架是gin以及gin-swagger

**Comment by gorexlv** [comment]
工程目录采用的是比较公认的接口，可能无法更改。
考虑swag有没有适应标准目录结构的参数？或者对gin-swagger做适应性二开？

**Comment by feixiao** [comment]
swag init 带参数可以解决这个问题
https://github.com/swaggo/swag

--generalInfo value, -g value      
 Go file path in which 'swagger general API Info' is written (default: "main.go")
--dir value, -d value               Directory you want to parse (default: "./")
