### ISSUE TITLE
Bug：panic of variable "span" rocketmq PushConsumer when EnableTrace is not set.

### ISSUE THREAD

**Issue by DenisYin66** [douyu/jupiter#571]
1. PushConsumer  dot not set EnableTrace 
2. consume message has error, the panic will be occurrence Unexpected 
![1669005015847](https://user-images.githubusercontent.com/37320260/202966202-dedce595-ce69-4bb9-9ca7-3f88852dd12f.png)

**Comment by hnlq715** [comment]
fixed in #572
