### ISSUE TITLE
[BUG]基于ETCD的GRPC服务

### ISSUE THREAD

**Issue by cw2018** [douyu/jupiter#64]
以下场景是基于ETCD的GRPC服务：

在GRPC服务端启动后，再启动GRPC客户端，一切正常。但是在此时把GRPC服务端重新启动后，GRPC客户端不管等多久，GRPC客户端都连接不上GRPC服务端。

**Comment by askuy** [comment]
我测试了你的这个场景，是正常的。

我测试了先启动客户端，后启动服务端，会有问题。报以下错误。
![image](https://user-images.githubusercontent.com/14119383/85204921-6b74f400-b34a-11ea-980e-745d215bee61.png)

我们看下这个问题

**Comment by cw2018** [comment]
以下场景是基于ETCD的GRPC服务：

在GRPC服务端启动后，再启动GRPC客户端，一切正常。但是在此时把GRPC服务端重新启动后，GRPC客户端不管等多久，GRPC客户端都连接不上GRPC服务端。

这种场景，偶然性比较大，不是每次都这样，不过我遇到几次

**Comment by askuy** [comment]
> 以下场景是基于ETCD的GRPC服务：
> 
> 在GRPC服务端启动后，再启动GRPC客户端，一切正常。但是在此时把GRPC服务端重新启动后，GRPC客户端不管等多久，GRPC客户端都连接不上GRPC服务端。
> 
> 这种场景，偶然性比较大，不是每次都这样，不过我遇到几次

好的。我昨天检查了服务端注册的etcd的key。我们看下客户端负载均衡机制

**Comment by zhouyg** [comment]
> 我测试了你的这个场景，是正常的。
> 
> 我测试了先启动客户端，后启动服务端，会有问题。报以下错误。
> ![image](https://user-images.githubusercontent.com/14119383/85204921-6b74f400-b34a-11ea-980e-745d215bee61.png)
> 
> 我们看下这个问题

修改配置，改成对应的服务名就行
address = "etcd:///服务名"

**Comment by cw2018** [comment]
我的是服务名，就是GRPC服务注册至ETCD的名字，现象是一样的，有时候还是不行？

**Comment by cw2018** [comment]
我的环境是：Centos7 + ETCD集群 + Supervisor管理golang服务的

**Comment by cw2018** [comment]
在GRPC服务中使用ETCD注册时，是否可以自动注册，不用填写的服务的端口号，怎么配置？

**Comment by cw2018** [comment]
![image](https://user-images.githubusercontent.com/3980453/85240528-154ba200-b46b-11ea-8093-88ca3b7022d6.png)

现在问题还是一样，不能使用？


![image](https://user-images.githubusercontent.com/3980453/85240430-bede6380-b46a-11ea-94fc-fd4ff35d00c2.png)

address = "etcd:///company_srv" 我现在填的服务名如上图中name，不知是否正确，如果不是，应该填那个？

**Comment by gorexlv** [comment]
> ![image](https://user-images.githubusercontent.com/3980453/85240528-154ba200-b46b-11ea-8093-88ca3b7022d6.png)
> 
> 现在问题还是一样，不能使用？
> 
> ![image](https://user-images.githubusercontent.com/3980453/85240430-bede6380-b46a-11ea-94fc-fd4ff35d00c2.png)
> 
> address = "etcd:///company_srv" 我现在填的服务名如上图中name，不知是否正确，如果不是，应该填那个？

是这样填的。能否与example对比一下, 看看是不是配置哪里不一样了？
example路径: https://github.com/douyu/jupiter/tree/master/example/grpc/etcd

**Comment by cw2018** [comment]
![image](https://user-images.githubusercontent.com/3980453/85242404-91e17f00-b471-11ea-88e5-f190bde07825.png)


我用你发的demo测试，也是一样错误

**Comment by gorexlv** [comment]
> 我用你发的demo测试，也是一样错误

请更新一下jupiter, 确认是一个bug, 已修复。

**Comment by cw2018** [comment]
![image](https://user-images.githubusercontent.com/3980453/85242436-ae7db700-b471-11ea-9307-daed4844148f.png)

**Comment by cw2018** [comment]
ok
