### ISSUE TITLE
support redis master-slave and fragmented redis switching functions

### ISSUE THREAD

**Issue by cw2018** [douyu/jupiter#65]
使用场景：

在本地使用的单个Redis：
redisStub := redis.StdRedisConfig("myredis").Build()

在正式环境使用的是Redis集群：
redisStub := redis.StdRedisClusterConfig("myredis").Build()

这样就产生一个问题，在代码里使用Redis的地方都需要判断是本地环境还是线上正式环境。
在框架中是否可以进一步封装，对于使用者不用管是什么环境，只需要传一个参数来确定是否为Redis集群？或者有更好的方案？

**Comment by askuy** [comment]
> 使用场景：
> 
> 在本地使用的单个Redis：
> redisStub := redis.StdRedisConfig("myredis").Build()
> 
> 在正式环境使用的是Redis集群：
> redisStub := redis.StdRedisClusterConfig("myredis").Build()
> 
> 这样就产生一个问题，在代码里使用Redis的地方都需要判断是本地环境还是线上正式环境。
> 在框架中是否可以进一步封装，对于使用者不用管是什么环境，只需要传一个参数来确定是否为Redis集群？或者有更好的方案？

这个可以规定，redis cluster和普通redis实现了一个redis interface。

然后你通过运行环境，在代码层面将不同的redis实例赋值给定义为interface的Redis Stub，如下所示

var RedisStub RedisInterface
if env =="prod" {
    RedisStub = redis.StdRedisClusterConfig("myredis").Build()
}else {
    RedisStub = redis.StdRedisConfig("myredis").Build()
}

type RedisInterface interface {
    Get()
    Set()
    ...
}

我们会看一下，普通redis和redis cluster的方法有没有统一起来。你也可以按我们方法，先自己试一下。

**Comment by cw2018** [comment]
ok

**Comment by OhBonsai** [comment]
Hi， 有人认领了这个Issue, 如果没有 我想Pick~

**Comment by askuy** [comment]
> Hi， 有人认领了这个Issue, 如果没有 我想Pick~
非常欢迎

**Comment by OhBonsai** [comment]
@askuy PTAL
