### ISSUE TITLE
[BUG]基于ETCD的GRPC服务动态端口的问题

### ISSUE THREAD

**Issue by cw2018** [douyu/jupiter#66]
基于ETCD的GRPC服务动态端口的问题：

如果GRPC服务基于ETCD，配置如下：
[jupiter.server.grpc]
    port = 0

如果先启动客户端，再启动服务端，现象同#64【基于ETCD的GRPC服务】一样的错误。

再正式环境中，经常会出现只更新某个服务的现象。

**Comment by gorexlv** [comment]
Hi 请问这个是否解决了您的问题？ https://github.com/douyu/jupiter/issues/64#issuecomment-647229358

**Comment by cw2018** [comment]
没有，这是我测试过的

**Comment by cw2018** [comment]
代码更新后，可以啦，谢谢

**Comment by gorexlv** [comment]
> 代码更新后，可以啦，谢谢

好的。如果没有更多问题，请帮忙关闭此issue
