### ISSUE TITLE
[BUG]redis客户端HIncrBy未返回值，总共两个地方啊，你们只修了一个

### ISSUE THREAD

**Issue by wangrongkang** [douyu/jupiter#67]
## Issue Description

Type: *bug report*

### Describe what happened
总共两个地方啊啊啊啊
```
  redis_cmds.go
``` 
和 
```
cluster_cmds.go
```

你们修了 `cluster_cmds.go`
没修 `redis_cmds.go` 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by askuy** [comment]
> ## Issue Description
> Type: _bug report_
> 
> ### Describe what happened
> 总共两个地方啊啊啊啊
> 
> ```
>   redis_cmds.go
> ```
> 
> 和
> 
> ```
> cluster_cmds.go
> ```
> 
> 你们修了 `cluster_cmds.go`
> 没修 `redis_cmds.go`
> 
> ### Describe what you expected to happen
> ### How to reproduce it (as minimally and precisely as possible)
> 
> ### Tell us your environment
> ### Anything else we need to know?

欢迎你来提一个pr。

**Comment by gorexlv** [comment]
如果要获取返回值，直接使用HIncrByWithErr会不会更好？

**Comment by mlboy** [comment]
感觉可以只有 HIncrByWithErr 方法，不需要分两类，无错误的，用户可以通过 "_" 自行放弃err， 每个都带一个WithErr感觉不是特别优雅。
