### ISSUE TITLE
[ci] 用actions 替换TravisCI

### ISSUE THREAD

**Issue by mlboy** [douyu/jupiter#76]
## Issue Description

是否有计划用actions 完全取代 TravisCI
感觉actions 速度上比 TravisCI更好点 ，另外也是github原生的。

Type: *feature request*

### Describe what feature you want

如果可以通过，我将尝试按照 .travis.yml 的功能 补充 .github/workflows/go.yml文件

**Comment by mlboy** [comment]
主要包括两方面内容：
1， go test 部分工作
2，上传代码覆盖工作

**Comment by mlboy** [comment]
# https://github.com/douyu/jupiter/pull/77

**Comment by gorexlv** [comment]
actions对services的支持怎么样？
