### ISSUE TITLE
opti: RestrictParallel execution optimization

### ISSUE THREAD

**Issue by zhouxiaohuan** [douyu/jupiter#778]
并发执行函数(xgo.RestrictParallel)优化协程执行顺序，通过chan去通知创建协程执行，而不是通过chan去通知协程继续执行。高并发情况下下降低内存开销和GMP调度压力。
![image](https://user-images.githubusercontent.com/48236214/224646073-ae383150-664b-4edf-ad34-ea46dd2dfb18.png)

**Comment by hnlq715** [comment]
Fixed in #779, thanks
