### ISSUE TITLE
[BUG] go get -u github.com/douyu/jupiter/tools/jupiter error

### ISSUE THREAD

**Issue by askuy** [douyu/jupiter#78]
## Issue Description

Type: *bug report*
go get -u github.com/douyu/jupiter/tools/jupiter error

![image](https://user-images.githubusercontent.com/14119383/85948371-1e64d380-b983-11ea-81b1-6e44602bbc93.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by gorexlv** [comment]
有环境和版本信息吗？
