### ISSUE TITLE
[BUG]HTTP port occupied

### ISSUE THREAD

**Issue by UnparalleledBeauty** [douyu/jupiter#8]
## Issue Description

Type: *bug report*

### Describe what happened
When the HTTP port is occupied, the program hangs and there is no log prompt

### Describe what you expected to happen
When the HTTP port is occupied, give a prompt and end the program

### How to reproduce it (as minimally and precisely as possible)
Using xecho module to open multiple HTTP services

**Comment by askuy** [comment]
FIX：see [fix: panic if governer address already in use](https://github.com/douyu/jupiter/blob/0f20623140d2e342fd232acda41a566b3988bf73/jupiter.go)
