### ISSUE TITLE
[BUG]xgin trace ctx

### ISSUE THREAD

**Issue by kevincqiang** [douyu/jupiter#81]
## Issue Description

Type: *bug report*

### Describe what happened
https://github.com/douyu/jupiter/blob/a1058be2af7473bf6c83a7b117994ac3a988c2e1/pkg/server/xgin/middleware.go#L186
这行代码没有将ctx添加到Request中，可以修改为：c.Request = c.Request.WithContext(ctx)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by mlboy** [comment]
thanks.
