### ISSUE TITLE
support config center?

### ISSUE THREAD

**Issue by codjust** [douyu/jupiter#9]
Have you considered supporting the microservice configuration center？
eg：apollo

**Comment by younglifestyle** [comment]
斗鱼有自家的配置中心，听说也会开源。

**Comment by gorexlv** [comment]
Yes. We plan to support Apollo /nacos, and in fact, it's quite easy to add Apollo /nacos adapters to Jupiter, have a look at: https://github.com/douyu/jupiter/blob/29d74dc50063ee9492c480724469c5c10e335763/pkg/conf/api.go#L24.

 Contribution is welcome.

**Comment by codjust** [comment]
got it! I will keep an eye on this project.
