### ISSUE TITLE
gorountine which is in hookSignals method can't stop normally

### ISSUE THREAD

**Issue by mlboy** [douyu/jupiter#92]
## Issue Description

Type: *bug report*

### Describe what happened

hookSignals 中有 for循环有些多余，没有可以让这个携程主动停止的方法，现在只能被动的通过 主进程停止后 被动停止。

现有逻辑：
hookSignals内协程，监听到信号后，向子服务发送关闭信号，并睡眠3秒，三秒后，继续循环监听信号
主进程等待所有子服务关闭后主进程关闭，主进程关闭后，被动的结束hookSignals内协程。

可以实现监听到一个信号后3秒若未处理完，仍继续监听信号通知。 （但这似乎用处不大）

调整方案：

直接去掉for循环 改为select 仅监听一次信号触发，接收到信号后直接 通知子服务关闭，之后 hookSignals内协程退出，主进程等待所有子服务退出，之后主进程退出。

现有逻辑倒是没有什么特别影响，但协成退出机制不够友好，是否做上述方案调整？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by askuy** [comment]
这个可以参考下nsq的信号量退出方案。有点改造成本

**Comment by mlboy** [comment]
另外，k8s 对信号处理别有一番思考，实现了二次监听中断信号，进行os.exit 强制退出

https://github.com/kubernetes/kubernetes/blob/5cc52ce5d3c1b4a0dff211cddd665a04b54c6074/staging/src/k8s.io/apiserver/pkg/server/signal.go

**Comment by mlboy** [comment]
tars 实现：

主线程通过 mainloop 卡住进程，  mainloop中主要是 通过一个chan 卡住的
https://github.com/TarsCloud/TarsGo/blob/204e08b762fb5853c57c6d7d0e50c25be6e4d63d/tars/application.go

**Comment by mlboy** [comment]
nsq 实现：
https://github.com/nsqio/nsq/blob/master/nsqd/nsqd.go
