### ISSUE TITLE
where is  deployment/docker-compose.yml ?

### ISSUE THREAD

**Issue by Gao-Vidor** [douyu/jupiter#964]
i can't find deployment/docker-compose.yml, when i run docker-compose -f deployment/docker-compose.yml up -d.

![image](https://github.com/douyu/jupiter/assets/23260976/b2ba5332-10bf-4f02-8b87-a3fce8187969)

**Comment by Gao-Vidor** [comment]
OK，i got it。 This doc should be updated。https://jupiter.douyu.com/jupiter/1.1quickstart.html#_1-1-2-%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE

**Comment by hnlq715** [comment]
Thanks, PR is welcom :-)
